### PR TITLE
Add Edges type and Box::extent() for its bottom right corner

### PR DESCRIPTION
**Pull request by outfoxxed**
For https://github.com/hyprwm/Hyprland/pull/7067

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
you need to clang-format this

**Comment by outfoxxed** [comment]
apparently clang format doesn't pick up tabs in comments, untabbed it

**Comment by vaxerski** [comment]
box.hpp

**Comment by outfoxxed** [comment]
mb

**Review by vaxerski — APPROVED** [review]
lgtm

**Pull request merged**
