### PR TITLE
Fix SOVERSION

### PR DESCRIPTION
**Pull request by zjeffer**
I didn't test this, but I think it would fix [this issue](https://aur.archlinux.org/packages/hyprland-git#comment-982720) in the hyprland-git AUR package, and people are also reporting the same issue [in the hyprutils-git AUR package](https://aur.archlinux.org/packages/hyprutils-git)

### CODE REVIEW

**Comment by zjeffer** [comment]
Or is there a reason that this was set to 1?

**Comment by vaxerski** [comment]
image

**Comment by zjeffer** [comment]
Recompiling doesn't seem to fix it:

```
ldd $(which Hyprland) | grep -i hypr
	libhyprcursor.so.0 => /usr/lib/libhyprcursor.so.0 (0x00007167ec1f2000)
	libhyprlang.so.2 => /usr/lib/libhyprlang.so.2 (0x00007167ec1bd000)
	libhyprutils.so.1 => /usr/lib/libhyprutils.so.1 (0x00007167ec1a9000)
	libhyprutils.so.0 => not found
```
It seems to want to find both `so.1` and `so.0`?

**Comment by vaxerski** [comment]
recompile _hyprland_

**Comment by zjeffer** [comment]
I did, using the hyprland-git package.

**Comment by vaxerski** [comment]
are you doing an XD where you have 2 hyprland binaries in /usr/bin and /usr/local/bin...?

`whereis Hyprland`

**Comment by zjeffer** [comment]
Nope, checked that too, I've made that mistake too often so I'm used to checking that now ;)

```
whereis Hyprland
Hyprland: /usr/bin/Hyprland /usr/share/man/man1/Hyprland.1.gz
```

**Comment by zjeffer** [comment]
Interestingly, removing my `libhyprutils.so.0` symlink (which I use as a temporary workaround) causes this:

```
ldd $(which Hyprland) | grep -i hypr
	libhyprcursor.so.0 => /usr/lib/libhyprcursor.so.0 (0x00007009bac1c000)
	libhyprlang.so.2 => /usr/lib/libhyprlang.so.2 (0x00007009babe7000)
	libhyprutils.so.1 => /usr/lib/libhyprutils.so.1 (0x00007009babd3000)
```
```
sudo rm /usr/lib/libhyprutils.so.0
```
```
ldd $(which Hyprland) | grep -i hypr
	libhyprcursor.so.0 => /usr/lib/libhyprcursor.so.0 (0x0000797556314000)
	libhyprlang.so.2 => /usr/lib/libhyprlang.so.2 (0x00007975562df000)
	libhyprutils.so.1 => /usr/lib/libhyprutils.so.1 (0x00007975562cb000)
	libhyprutils.so.0 => not found
```
Why is it not looking for libhyprutils.so.0 until I remove it?

**Comment by vaxerski** [comment]
something's fucked with your compile

**Comment by zjeffer** [comment]
I'll see what happens if I compile manually.

Either way, I'm not the only person this happens to: two other people in the hyprland-git AUR package are complaining about this

**Comment by vaxerski** [comment]
I blame the aur package

**Comment by zjeffer** [comment]
Installing Hyprland to /usr/local/ by cloning and running `make all && sudo make install`, and installing hyprutils using the Readme's instructions, has seemingly the same effect:

```
ldd /usr/local/bin/Hyprland | grep -i hypr
	libhyprlang.so.2 => /usr/lib/libhyprlang.so.2 (0x000079f2d5bdb000)
	libhyprcursor.so.0 => /usr/lib/libhyprcursor.so.0 (0x000079f2d5b8a000)
	libhyprutils.so.1 => /usr/lib/libhyprutils.so.1 (0x000079f2d5b76000)
	libhyprutils.so.0 => not found
```

**Comment by zjeffer** [comment]
```
ldd $(which Hyprland) | grep -i hypr
	libhyprcursor.so.0 => /usr/lib/libhyprcursor.so.0 (0x00007d2a12063000)
	libhyprlang.so.2 => /usr/lib/libhyprlang.so.2 (0x00007d2a1202e000)
	libhyprutils.so.1 => /usr/lib/libhyprutils.so.1 (0x00007d2a1201a000)
	libhyprutils.so.0 => not found
```

```
ldd $(which hyprctl) | grep -i hypr
	libhyprutils.so.1 => /usr/lib/libhyprutils.so.1 (0x000073509da24000
```
hyprctl for some reason doesn't try to find .so.0

**Comment by zjeffer** [comment]
@vaxerski Finally found it: I noticed /usr/lib/libhyprlang.so was linked to `libhyprutils.so.0`:

```
ldd libhyprlang.so
	linux-vdso.so.1 (0x0000735979b37000)
	libhyprutils.so.0 => not found
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x0000735979800000)
	libm.so.6 => /usr/lib/libm.so.6 (0x0000735979715000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007359796e8000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007359794fc000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x0000735979b39000)
```

After reinstalling with `paru -S hyprlang-git`, both `Hyprland` and `/usr/lib/libhyprlang.so` were only linked to `libhyprutils.so.1`, not `.so.0`.

**Pull request closed without merging**
